# Generated by Django 6.0.6 on 2026-06-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
