# Generated by Django 6.0.6 on 2026-07-01 12:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP'),
        ),
    ]
